service:
  name: serverless-sample

plugins:
  - serverless-webpack

provider:
  name: aws
  stage: dev
# profile: playground-user
  runtime: nodejs14.x
  region: eu-west-1
  memorySize: 256
  timeout: 30
  iam:
    role:
      name: serverless-sample-lambda-role

functions:
  log:
    handler: src/index.handler
    events:
      - http:
          method: post
          path: sample
